# -*- coding: utf-8 -*-
"""EDA on Make, Model, Base MSRP, Electric Range, CAFV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bcw3_jyyPT1psKYYu84N5j9AS4YTNNFB
"""

# Commented out IPython magic to ensure Python compatibility.
#Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

#to display plots inline
# %matplotlib inline

from google.colab import drive

# Mount Google Drive
drive.mount('/content/gdrive')

# Access your dataset
data_path = '/content/gdrive/My Drive/Colab Notebooks/Electiric vehical/cleaned_data.csv'

df = pd.read_csv(data_path)
# Display the first few rows of the DataFrame
df.head()

df.info()

df.describe()

"""**Analyze Consumer Preferences by Vehicle Type**

**Distribution of BEVs vs. PHEVs**
"""

# Count the number of BEVs and PHEVs
ev_type_distribution = df['Electric Vehicle Type'].value_counts()

# Display the distribution
print(ev_type_distribution)

# Plot the distribution
import matplotlib.pyplot as plt
ev_type_distribution.plot(kind='bar', color=['blue', 'green'])
plt.title('Distribution of BEVs vs. PHEVs')
plt.xlabel('Electric Vehicle Type')
plt.ylabel('Number of Vehicles')
plt.show()

"""**Findings**

- BEVs Dominance: The number of BEVs is significantly higher than PHEVs, with around 160,000 BEVs compared to approximately 45,000 PHEVs.

- Consumer Preference: This indicates a clear consumer preference for fully electric vehicles (BEVs) over hybrids (PHEVs).

**Distribution of BEVs vs. PHEVs by County**
"""

# Group by County and Electric Vehicle Type
ev_type_by_county = df.groupby(['County', 'Electric Vehicle Type']).size().unstack()

# Display the distribution
print(ev_type_by_county)

# Plot the distribution
ev_type_by_county.plot(kind='bar', stacked=True, figsize=(35, 10), color=['blue', 'green'])
plt.title('BEVs vs. PHEVs Distribution by County')
plt.xlabel('County')
plt.ylabel('Number of Vehicles')
plt.legend(title='Electric Vehicle Type')
plt.show()

"""**Findings**

- King County stands out with a significantly higher number of both BEVs and PHEVs compared to other counties. This further emphasizes King County as a major hub for electric vehicle adoption in Washington State.

- Other counties such as Snohomish, Pierce, and Clark show moderate levels of BEV and PHEV adoption, but these numbers are much lower compared to King County. Most other counties have relatively low counts, indicating slower adoption in more rural or less densely populated areas.

- Across most counties, BEVs are more prevalent than PHEVs, which is consistent with the general preference for fully electric vehicles.

**Analyze Popular Makes and Models**

**Most Popular Makes**
"""

# Count the number of vehicles by make
make_distribution = df['Make'].value_counts()

# Display the top 10 most popular makes
print(make_distribution.head(10))

# Plot the top 10 most popular makes
make_distribution.head(10).plot(kind='bar', color='skyblue')
plt.title('Top 10 Most Popular EV Makes')
plt.xlabel('Make')
plt.ylabel('Number of Vehicles')
plt.show()

"""**Findings**

- Tesla is by far the most popular EV make, with over 80,000 vehicles registered, significantly outpacing all other manufacturers. This shows Tesla's strong market presence in the EV sector.

- Chevrolet and Nissan follow, but with a much lower number of vehicles compared to Tesla, each having around 10,000 to 15,000 vehicles.

- The remaining brands like Ford, Kia, BMW, Toyota, and Volkswagen have smaller but still notable shares in the EV market. Their numbers range from around 5,000 to 10,000 vehicles.

- Hyundai and Jeep make up the bottom of the top 10, indicating that they are less popular EV choices among consumers compared to other brands.

**Most Popular Models**
"""

# Count the number of vehicles by model
model_distribution = df['Model'].value_counts()

# Display the top 10 most popular models
print(model_distribution.head(10))

# Plot the top 10 most popular models
model_distribution.head(10).plot(kind='bar', color='orange')
plt.title('Top 10 Most Popular Models')
plt.xlabel('Model')
plt.ylabel('Number of Vehicles')
plt.show()

"""**Findings**

- Tesla's Model Y is the most popular model, with over 40,000 vehicles, followed by the Model 3 with over 30,000 vehicles. These two models dominate the EV market, highlighting Tesla's strong presence.

- The Nissan Leaf is the third most popular model, with a noticeable drop in numbers compared to Tesla models, around 15,000 vehicles.

- The Tesla Model S and Model X are also in the top 10, though with fewer registrations compared to the Model Y and Model 3, showing that Tesla's other offerings are also popular, albeit to a lesser extent.

- The Chevrolet Bolt EV, Chevrolet Volt, Volkswagen ID.4, Ford Mustang Mach-E, and Jeep Wrangler round out the top 10, each with a few thousand vehicles. These models represent a mix of traditional automakers entering the EV market.

**Analyze Price Sensitivity**

Distribution of Base MSRP
"""

# Plot the distribution of Base MSRP
plt.figure(figsize=(10, 6))
plt.hist(df['Base MSRP'], bins=50, color='purple', edgecolor='black')
plt.title('Distribution of Base MSRP')
plt.xlabel('Base MSRP ($)')
plt.ylabel('Number of Vehicles')
plt.show()

"""**Electric Range Analysis**

**Distribution of Electric Range**
"""

# Plot the distribution of Electric Range
plt.figure(figsize=(10, 6))
plt.hist(df['Electric Range'], bins=50, color='green', edgecolor='black')
plt.title('Distribution of Electric Range')
plt.xlabel('Electric Range (miles)')
plt.ylabel('Number of Vehicles')
plt.show()

"""**Findings**

- The majority of vehicles have an electric range close to 0 miles, which likely represents plug-in hybrid electric vehicles (PHEVs) that have a limited electric-only range or vehicles with a very low state of charge (SOC) in the dataset.

- There are smaller peaks around 100-150 miles and again around 200-300 miles. These peaks likely represent the fully electric vehicles (BEVs) that typically have longer ranges, such as Tesla models and other long-range electric vehicles.


- The tail end of the distribution indicates that there are fewer vehicles with very high electric ranges, above 200 miles, but these are significant in terms of their importance for long-distance driving.

**Most Popular Makes by County**

**Calculate the Most Popular Make in Each County**
"""

# Group by County and Make, then count the number of vehicles for each make in each county
make_by_county = df.groupby(['County', 'Make']).size().reset_index(name='Count')

# Sort the values within each county to get the most popular make
most_popular_make_by_county = make_by_county.loc[make_by_county.groupby('County')['Count'].idxmax()]

# Display the most popular make by county
print(most_popular_make_by_county)

"""**Visualize the Most Popular Makes by County**"""

import seaborn as sns
import matplotlib.pyplot as plt

# Plot the most popular make by county
plt.figure(figsize=(12, 40))
sns.barplot(x='Count', y='County', hue='Make', data=most_popular_make_by_county, dodge=False)
plt.title('Most Popular Car Maker by County')
plt.xlabel('Number of Vehicles')
plt.ylabel('County')
plt.show()

"""**Findings**

- Tesla is overwhelmingly the most popular EV maker in the majority of counties, as indicated by the significant number of Tesla vehicles in these areas. Counties like King, Snohomish, and Pierce show especially high numbers of Tesla vehicles, reflecting the brand's strong market presence.

- While Tesla dominates, there are some counties where other EV makers, such as Chevrolet, Nissan, and BMW, are more popular. This variation indicates that while Tesla has a broad appeal, other manufacturers are also significant players in certain regions.


- The chart highlights regional preferences, where certain counties might favor one brand over another, possibly due to factors such as local dealerships, consumer demographics, or infrastructure support.

**Identify the Top 20 Counties with the Most Electric Vehicles**
"""

# Group by County and count the number of electric vehicles in each county
ev_count_by_county = df.groupby('County').size().reset_index(name='Total EVs')

# Sort counties by the total number of electric vehicles and get the top 20
top_20_counties = ev_count_by_county.sort_values(by='Total EVs', ascending=False).head(20)

# Display the top 20 counties
print(top_20_counties)

"""**Determine the Most Popular Make in Each of the Top 20 Counties**"""

# Filter the dataset to include only the top 20 counties
df_top_20_counties = df[df['County'].isin(top_20_counties['County'])]

# Group by County and Make, then count the number of vehicles for each make in each county
make_by_top_20_counties = df_top_20_counties.groupby(['County', 'Make']).size().reset_index(name='Count')

# Sort the values within each county to get the most popular make
most_popular_make_by_top_20_counties = make_by_top_20_counties.loc[make_by_top_20_counties.groupby('County')['Count'].idxmax()]

# Display the most popular make by the top 20 counties
print(most_popular_make_by_top_20_counties)

"""**Visualize the Most Popular Makes by Top 20 Counties**"""

import seaborn as sns
import matplotlib.pyplot as plt

# Plot the most popular make by the top 20 counties
plt.figure(figsize=(14, 10))
sns.barplot(x='Count', y='County', hue='Make', data=most_popular_make_by_top_20_counties, dodge=False)
plt.title('Most Popular Make by Top 20 Counties')
plt.xlabel('Number of Vehicles')
plt.ylabel('County')
plt.show()

"""**Findings**

- Tesla is the most popular EV make in almost all of the top 20 counties, with King County having an exceptionally high number of Tesla vehicles compared to other counties. This reaffirms Tesla's strong market presence in Washington State.

- King County alone has more Tesla vehicles than any other county, reflecting its status as a major hub for EV adoption. The number of Teslas in King County significantly overshadows the numbers in other counties.

- Snohomish and Pierce Counties also show a considerable number of Tesla vehicles, though still much lower than King County. Clark County follows with a moderate number of Teslas.

- Nissan appears as the most popular make in San Juan County, but its presence is minimal compared to Tesla's dominance across the other counties.

**Most Popular Makes by City**

**Calculate the Most Popular Make in Each City**
"""

# Group by City and Make, then count the number of vehicles for each make in each city
make_by_city = df.groupby(['City', 'Make']).size().reset_index(name='Count')

# Sort the values within each city to get the most popular make
most_popular_make_by_city = make_by_city.loc[make_by_city.groupby('City')['Count'].idxmax()]

# Display the most popular make by city
print(most_popular_make_by_city.head(20))  # Display the top 20 cities as an example

"""**Visualize the Most Popular Makes by City**"""

# Plot the most popular make by city (for the top 20 cities)
plt.figure(figsize=(12, 8))
sns.barplot(x='Count', y='City', hue='Make', data=most_popular_make_by_city.head(20), dodge=False)
plt.title('Most Popular Car Maker by City (Top 20 Cities)')
plt.xlabel('Number of Vehicles')
plt.ylabel('City')
plt.show()

"""**Findings**

- Tesla is overwhelmingly the most popular EV make in most of the top 20 cities, particularly in cities like Anacortes, Allyn, and Algona. This consistent dominance underscores Tesla's market strength across various cities.

- The number of Tesla vehicles is notably high in Anacortes, where it far exceeds the number of Tesla vehicles in other cities. Allyn and Aberdeen also show a significant number of Teslas, though still much less compared to Anacortes.

- Other car makers like Ford, Nissan, MINI, and Rivian appear in a few cities but with much lower counts compared to Tesla. For example, Ford shows up in Acme, and Nissan in Alderwood Manor, but their presence is minimal.

- In some cities, a single EV make like Tesla completely dominates the market, while in others, there is at least some presence of alternative makes, though still dwarfed by Tesla.

**To analyze the growth of different makes and models of electric vehicles by model year**

**Group the Data by Model Year, Make, and Model**
"""

# Group by Model Year, Make, and Model, then count the number of vehicles for each combination
make_model_growth = df.groupby(['Model Year', 'Make', 'Model']).size().reset_index(name='Count')

# Display the first few rows to verify the grouping
print(make_model_growth.head())

"""**Analyze Growth Trends Over Time**"""

# Identify the top 5 makes and models with the most vehicles overall
top_makes_models = make_model_growth.groupby(['Make', 'Model'])['Count'].sum().nlargest(5).reset_index()

# Filter the data to include only the top makes and models
make_model_growth_top = make_model_growth[(make_model_growth['Make'].isin(top_makes_models['Make'])) &
                                          (make_model_growth['Model'].isin(top_makes_models['Model']))]

# Display the filtered data
print(make_model_growth_top.head())

"""**Visualize the Growth of Makes and Models Over the Years**"""

import seaborn as sns
import matplotlib.pyplot as plt

# Plot the growth of makes and models over the years
plt.figure(figsize=(14, 8))
sns.lineplot(data=make_model_growth, x='Model Year', y='Count', hue='Make', style='Model', markers=True, dashes=False)
plt.title('Growth of Makes and Models by Year')
plt.xlabel('Model Year')
plt.ylabel('Number of Vehicles')
plt.legend(title='Make and Model', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

"""**Findings**

- Tesla models, particularly those around the 2020s, show a significant spike, indicating rapid adoption and growth during this period. Tesla's growth outpaces that of other manufacturers by a substantial margin.

- The years around 2020 to 2021 witnessed the most significant increase in EV registrations across various makes and models. This indicates a broader market acceptance and the impact of new EV models entering the market.

- While Tesla leads by a large margin, other brands like Chevrolet, Ford, and Nissan also show growth, although at a much lower scale. This suggests increasing competition in the EV market with more manufacturers offering electric models.

- Before 2015, the market was relatively small with limited EV models. Post-2015, there is a noticeable increase in the diversity of models available, reflecting the industry's rapid expansion and innovation in EV technology.

- The chart shows that some models have peaks indicating popularity spikes, but these are dwarfed by the peaks associated with Tesla models, which dominate the overall landscape.
"""

# Plot the growth of top makes and models over the years
plt.figure(figsize=(14, 8))
sns.lineplot(data=make_model_growth_top, x='Model Year', y='Count', hue='Make', style='Model', markers=True, dashes=False)
plt.title('Growth of Top Makes and Models by Year')
plt.xlabel('Model Year')
plt.ylabel('Number of Vehicles')
plt.legend(title='Make and Model', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

"""**Findings**

- Tesla's Model Y and Model 3 exhibit the most significant growth, with a sharp increase in registrations starting around 2019 and peaking in 2021. The Model Y shows the highest peak, indicating it is currently the most popular model.

- Other models like the Nissan Leaf, Tesla Model S, and Chevrolet Bolt EV show steadier growth with fewer fluctuations compared to Tesla’s newer models. The Nissan Leaf, in particular, has consistent registrations over the years but does not match the peaks of Tesla's models.

- There is a noticeable decline in the number of vehicles registered after the 2021 peak across all models. This could indicate market saturation, changes in consumer preferences, or a temporary slowdown in new vehicle registrations.

- Despite the overall decline, Tesla models continue to dominate the EV market, significantly outpacing other models in terms of growth and total numbers.

**To analyze the Base Manufacturer's Suggested Retail Price (MSRP) for each maker (brand).**

**Calculate the Average Base MSRP for Each Maker**
"""

# Group by Make and calculate the average Base MSRP
average_msrp_by_make = df.groupby('Make')['Base MSRP'].mean().reset_index()

# Sort the results by Base MSRP in descending order to see the most expensive makers first
average_msrp_by_make = average_msrp_by_make.sort_values(by='Base MSRP', ascending=False)

# Display the results
print(average_msrp_by_make)

"""**Visualize the Base MSRP for Each Maker**"""

import matplotlib.pyplot as plt
import seaborn as sns

# Plot the average Base MSRP by Make
plt.figure(figsize=(14, 8))
sns.barplot(x='Base MSRP', y='Make', data=average_msrp_by_make, palette='viridis')

# Add the exact values on top of the bars
for index, value in enumerate(average_msrp_by_make['Base MSRP']):
    plt.text(value, index, f'${value:,.2f}', va='center')

plt.title('Average Base MSRP by Car Maker')
plt.xlabel('Average Base MSRP ($)')
plt.ylabel('Make')
plt.show()

"""**Findings**

- WHEEGO ELECTRIC CARS brand shows the highest average base MSRP at $32,995.00, making it the most expensive among the listed brands.

- MINI, VOLVO, FISKER, BMW brands have significant average base MSRPs, with MINI leading this group at $5,724.93.
- The other brands range from $3,015.35 (BMW) to $3,439.01 (VOLVO).

- A large number of car makers, including popular brands like Tesla, Nissan, Ford, and Chevrolet, show an MSRP of $0. This might suggest that MSRP data for these brands is missing or was not included in the dataset.

- Interestingly, Tesla is listed with a very low average base MSRP of $920.69, which seems inconsistent with market prices, indicating a potential data issue or that only a specific subset of Tesla vehicles was considered.

**What is the distribution of Base MSRP across different regions (counties and cities)?**

**Calculate the Average Base MSRP by County**
"""

# Group by County and calculate the average Base MSRP
average_msrp_by_county = df.groupby('County')['Base MSRP'].mean().reset_index()

# Sort the results by Base MSRP in descending order to see the most expensive counties first
average_msrp_by_county = average_msrp_by_county.sort_values(by='Base MSRP', ascending=False)

# Display the results
print(average_msrp_by_county)

"""**Average Base MSRP by City**"""

# Group by City and calculate the average Base MSRP
average_msrp_by_city = df.groupby('City')['Base MSRP'].mean().reset_index()

# Sort the results by Base MSRP in descending order to see the most expensive cities first
average_msrp_by_city = average_msrp_by_city.sort_values(by='Base MSRP', ascending=False)

# Display the results
print(average_msrp_by_city)

"""**Visualize the Distribution Using Box Plots**"""

import seaborn as sns
import matplotlib.pyplot as plt

# Plot the distribution of Base MSRP by County
plt.figure(figsize=(14, 50))
sns.boxplot(x='Base MSRP', y='County', data=df, palette='coolwarm')
plt.title('Distribution of Base MSRP by County')
plt.xlabel('Base MSRP ($)')
plt.ylabel('County')
plt.show()

"""**Findings**

- The chart shows a significant variation in the base MSRP across different counties, indicating that the price points for electric vehicles (EVs) can differ substantially depending on the region.

- Some counties have higher average MSRPs, with Los Angeles and another county standing out with particularly high ranges, suggesting that more expensive EV models might be more popular or more available in these areas.

- Other counties show much lower base MSRPs, indicating a preference or availability of less expensive EV models.

- There are some outliers in the data, which could represent either very high-end models or data points with incorrect or exceptional pricing.
"""

# Plot the distribution of Base MSRP by City
plt.figure(figsize=(15, 100))
sns.boxplot(x='Base MSRP', y='City', data=df, palette='coolwarm')
plt.title('Distribution of Base MSRP by City')
plt.xlabel('Base MSRP ($)')
plt.ylabel('City')
plt.show()

"""**Findings**

- The chart reveals significant variations in the base MSRP across different cities, indicating that the price points for electric vehicles (EVs) can differ substantially depending on the city.

- Some cities have notably higher average MSRPs, with a few standing out with particularly high ranges. This suggests that more expensive EV models might be more popular or more available in these areas.

- Many cities display lower base MSRPs, indicating a preference or availability of less expensive EV models.

- There are outliers in the data, representing either very high-end models or potentially incorrect or exceptional pricing data.

**Is there a relationship between Base MSRP and the type of EV (BEV vs. PHEV)?**

**Compare the Average Base MSRP between BEVs and PHEVs**
"""

# Group by Electric Vehicle Type and calculate the average Base MSRP
average_msrp_by_ev_type = df.groupby('Electric Vehicle Type')['Base MSRP'].mean().reset_index()

# Display the results
print(average_msrp_by_ev_type)

"""**Visualize the Distribution of Base MSRP for BEVs and PHEVs**"""

import seaborn as sns
import matplotlib.pyplot as plt

# Plot the distribution of Base MSRP for BEVs vs. PHEVs
plt.figure(figsize=(10, 6))
sns.boxplot(x='Electric Vehicle Type', y='Base MSRP', data=df, palette='Set2')
plt.title('Distribution of Base MSRP by EV Type (BEV vs. PHEV)')
plt.xlabel('Electric Vehicle Type')
plt.ylabel('Base MSRP ($)')
plt.show()

"""**Findings**

- Both BEVs and PHEVs show the presence of significant outliers in their base MSRP. These outliers indicate that there are a few very high-priced vehicles in both categories.

- The bulk of the data for both BEVs and PHEVs is clustered near the lower end of the MSRP scale, suggesting that most vehicles in both categories have a relatively low base price.

- The PHEVs appear to have slightly more high-priced outliers compared to BEVs, although the difference is not drastic.

- The main body of the MSRP data for both BEVs and PHEVs is tightly clustered at the lower end, indicating that most of these vehicles are priced similarly.

**How does Electric Range vary across different makes and models?**
"""

# Group by Make and Model, then calculate the average Electric Range
average_range_by_make_model = df.groupby(['Make', 'Model'])['Electric Range'].mean().reset_index()

# Sort the results by Electric Range in descending order to see the models with the highest range first
average_range_by_make_model = average_range_by_make_model.sort_values(by='Electric Range', ascending=False)

# Display the results
print(average_range_by_make_model)

import seaborn as sns
import matplotlib.pyplot as plt

# Plot the distribution of Electric Range by Make
plt.figure(figsize=(14, 8))
sns.boxplot(x='Electric Range', y='Make', data=df, palette='Set3')
plt.title('Distribution of Electric Range by Make')
plt.xlabel('Electric Range (miles)')
plt.ylabel('Make')
plt.show()

"""**Findings**

- Tesla vehicles have the highest range among all car makes, with most of their vehicles offering well above 200 miles of electric range. Tesla's box plot is also the longest, indicating that its models span a wide range of electric mileages, with some outliers exceeding 300 miles.

- Chevrolet and Nissan also offer vehicles with a relatively high range, with many models clustered around 100-200 miles. These makes appear to be the next most competitive in terms of electric range after Tesla.

- Other car makers, such as BMW, Ford, and Audi, offer vehicles with a range of 50-150 miles, indicating more variability in their electric vehicle offerings.

- Several makes, such as SMART, MINI, and FIAT, have vehicles with much lower electric ranges, generally below 50 miles. These vehicles likely cater to urban drivers with shorter commutes.

- Many makes show a number of outliers indicating the presence of models with significantly higher or lower ranges than the median. This suggests diversity within the makes in terms of their vehicle offerings.

**Are vehicles with a higher Electric Range more popular in certain regions?**

**Segment the Data into Electric Range Categories**
"""

# Define Electric Range categories
bins = [0, 100, 200, 300, 400, 500, 1000]  # Adjust the bins based on your data
labels = ['0-100 miles', '101-200 miles', '201-300 miles', '301-400 miles', '401-500 miles', '500+ miles']

# Create a new column for Electric Range Category
df['Range Category'] = pd.cut(df['Electric Range'], bins=bins, labels=labels, right=False)

# Display the first few rows to verify
print(df[['Electric Range', 'Range Category']].head())

"""**Calculate the Popularity of Each Range Category by Region**

Popularity by County
"""

# Group by County and Range Category to count the number of vehicles in each category per county
range_popularity_by_county = df.groupby(['County', 'Range Category']).size().reset_index(name='Count')

# Display the results
print(range_popularity_by_county)

"""Popularity by City"""

# Group by City and Range Category to count the number of vehicles in each category per city
range_popularity_by_city = df.groupby(['City', 'Range Category']).size().reset_index(name='Count')

# Display the results
print(range_popularity_by_city)

"""**Visualize the Distribution to See Regional Preferences**"""

# Visualize Popularity by County

import seaborn as sns
import matplotlib.pyplot as plt

# Plot the distribution of Electric Range categories by County
plt.figure(figsize=(14, 80))
sns.barplot(x='Count', y='County', hue='Range Category', data=range_popularity_by_county, palette='viridis')
plt.title('Popularity of Electric Range Categories by County')
plt.xlabel('Number of Vehicles')
plt.ylabel('County')
plt.legend(title='Electric Range Category', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

"""**Findings**

- The counties with the highest number of vehicles, particularly King County, show a strong preference for vehicles with a range of 300+ miles. This suggests that in more populous or affluent counties, consumers are opting for longer-range EVs, which are likely more expensive and offer more convenience for longer trips.

- In some counties, there are noticeable counts of vehicles in the lower range categories (0-100 miles and 101-200 miles). This indicates that in certain regions, possibly where EV adoption is just beginning or where driving distances are typically shorter, consumers are opting for more affordable, shorter-range vehicles.

- Many counties show little to no adoption across all range categories. This could be due to lower overall EV adoption in these regions, possibly influenced by factors such as lack of infrastructure, economic factors, or lower consumer awareness.

- A few counties, like King, Snohomish, and Pierce, have a much higher number of vehicles across multiple range categories, highlighting their role as major hubs of EV adoption within the state.
"""

# Visualize Popularity by City

# Plot the distribution of Electric Range categories by City (for top cities)
plt.figure(figsize=(10, 100))
sns.barplot(x='Count', y='City', hue='Range Category', data=range_popularity_by_city, palette='viridis')
plt.title('Popularity of Electric Range Categories by City')
plt.xlabel('Number of Vehicles')
plt.ylabel('City')
plt.legend(title='Electric Range Category', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

"""**Findings**

- The majority of cities with significant EV adoption show a strong preference for vehicles with a range of 300+ miles. This aligns with the trend seen in counties where longer-range vehicles are more popular in urban and affluent areas.

- Some cities show notable adoption of EVs in the lower range categories (0-100 miles and 101-200 miles). This could indicate early-stage adoption in these cities, where consumers might be opting for more affordable EV options, or where shorter driving distances make lower-range EVs practical.

- A large number of cities show very low or no adoption across all range categories. This suggests that EV adoption is still limited in many smaller or rural cities, potentially due to lack of infrastructure, economic factors, or lower awareness of EV options.

- Cities with higher adoption levels across multiple range categories stand out, highlighting these areas as significant hubs for EV usage. This trend is consistent with what has been observed in the county-level analysis.

**How does Clean Alternative Fuel Vehicle (CAFV) Eligibility affect consumer choices?**


**To analyze how Clean Alternative Fuel Vehicle (CAFV) Eligibility affects consumer choices, I'll focus on the top 20 counties and top 20 cities by the number of vehicles.**
"""

# Identify the Top 20 Counties and Cities

# Group by County and count the number of vehicles
vehicle_count_by_county = df.groupby('County').size().reset_index(name='Total Vehicles')

# Sort and get the top 20 counties
top_20_counties = vehicle_count_by_county.sort_values(by='Total Vehicles', ascending=False).head(20)

# Filter the dataset to include only these top 20 counties
df_top_20_counties = df[df['County'].isin(top_20_counties['County'])]

# Display the top 20 counties
print(top_20_counties)

# Top 20 Cities by Vehicle Count

# Group by City and count the number of vehicles
vehicle_count_by_city = df.groupby('City').size().reset_index(name='Total Vehicles')

# Sort and get the top 20 cities
top_20_cities = vehicle_count_by_city.sort_values(by='Total Vehicles', ascending=False).head(20)

# Filter the dataset to include only these top 20 cities
df_top_20_cities = df[df['City'].isin(top_20_cities['City'])]

# Display the top 20 cities
print(top_20_cities)

# Analyze the Distribution of CAFV-Eligible vs. Non-Eligible Vehicles

# Distribution in Top 20 Counties

# Group by County and CAFV Eligibility, then count the number of vehicles
cafv_distribution_by_county = df_top_20_counties.groupby(['County', 'Clean Alternative Fuel Vehicle (CAFV) Eligibility']).size().reset_index(name='Count')

# Display the results
print(cafv_distribution_by_county)

# Distribution in Top 20 Cities

# Group by City and CAFV Eligibility, then count the number of vehicles
cafv_distribution_by_city = df_top_20_cities.groupby(['City', 'Clean Alternative Fuel Vehicle (CAFV) Eligibility']).size().reset_index(name='Count')

# Display the results
print(cafv_distribution_by_city)

# Visualize the Results Using Bar Charts

import seaborn as sns
import matplotlib.pyplot as plt

# Plot the distribution of CAFV-eligible vs. non-eligible vehicles by County
plt.figure(figsize=(14, 8))
sns.barplot(x='Count', y='County', hue='Clean Alternative Fuel Vehicle (CAFV) Eligibility', data=cafv_distribution_by_county, palette='Set2')
plt.title('CAFV-Eligible vs. Non-Eligible Vehicles by Top 20 Counties')
plt.xlabel('Number of Vehicles')
plt.ylabel('County')
plt.legend(title='CAFV Eligibility')
plt.show()

"""**Findings**

- King County has the highest number of CAFV-eligible vehicles by a significant margin, indicating that a large portion of its electric vehicle fleet meets the criteria for clean alternative fuel vehicles.
- However, King County also has a considerable number of vehicles where eligibility is unknown, suggesting that further research or data collection may be needed to fully understand the CAFV potential in this county.
-Counties such as Snohomish, Pierce, and Clark also show a reasonable number of CAFV-eligible vehicles, reflecting their urban nature and more extensive EV adoption.
- These counties also have a significant number of vehicles where eligibility is unknown, which might indicate a similar need for more detailed data.
- Rural counties like Grays Harbor, Island, and Clallam have much lower numbers of CAFV-eligible vehicles, which is consistent with the overall lower adoption of EVs in these areas.
- The presence of non-eligible vehicles due to low battery range is also more noticeable in these counties, likely reflecting the older or less advanced EVs that may be more prevalent in rural areas.
- Across several counties, there is a significant proportion of vehicles where CAFV eligibility is unknown, mainly due to the lack of information on battery range.
"""

# Plot the distribution of CAFV-eligible vs. non-eligible vehicles by City
plt.figure(figsize=(14, 8))
sns.barplot(x='Count', y='City', hue='Clean Alternative Fuel Vehicle (CAFV) Eligibility', data=cafv_distribution_by_city, palette='Set2')
plt.title('CAFV-Eligible vs. Non-Eligible Vehicles by Top 20 Cities')
plt.xlabel('Number of Vehicles')
plt.ylabel('City')
plt.legend(title='CAFV Eligibility')
plt.show()

"""**Findings**

- Seattle has the highest number of CAFV-eligible vehicles, which aligns with its overall leadership in EV adoption. However, Seattle also has a large number of vehicles where eligibility is unknown, indicating a need for further investigation to determine the full potential for CAFV.

- Across most cities, there is a notable portion of vehicles where the eligibility is unknown due to the lack of data on battery range. This is especially prominent in cities like Bellevue, Bothell, and Sammamish. Addressing this data gap could provide clearer insights into the potential for CAFV expansion.

- Cities such as Bellevue, Redmond, and Kirkland show a moderate number of CAFV-eligible vehicles, reflecting their suburban nature and significant EV adoption rates. These cities also have a considerable number of vehicles with unknown eligibility, similar to the trend observed in Seattle.

- Smaller cities like Tukwila, Woodinville, and Mercer Island have fewer CAFV-eligible vehicles. The lower overall EV adoption in these areas likely contributes to this trend.

**Is there a correlation between CAFV Eligibility and Base MSRP or Electric Range?**

**Analyze the Relationship Between CAFV Eligibility and Base MSRP**
"""

# Group by CAFV Eligibility and calculate the mean Base MSRP
msrp_summary_by_cafv = df.groupby('Clean Alternative Fuel Vehicle (CAFV) Eligibility')['Base MSRP'].describe()

# Display the summary statistics
print(msrp_summary_by_cafv)

import seaborn as sns
import matplotlib.pyplot as plt

# Box plot of Base MSRP by CAFV Eligibility
plt.figure(figsize=(10, 6))
sns.boxplot(x='Clean Alternative Fuel Vehicle (CAFV) Eligibility', y='Base MSRP', data=df, palette='Set3')
plt.title('Base MSRP by CAFV Eligibility')
plt.xlabel('CAFV Eligibility')
plt.ylabel('Base MSRP ($)')
plt.show()

"""**Findings**

- The higher base MSRP vehicles (over $30,000) are distributed across all three categories of CAFV eligibility, including Clean Alternative Fuel Vehicle Eligible, Not Eligible, and Eligibility Unknown.

- The most expensive vehicles tend to cluster around $40,000 to $50,000 across all eligibility categories.

- A significant portion of the vehicles across all eligibility categories has a base MSRP near zero or very low, which could indicate the presence of data inaccuracies or incomplete pricing information in the dataset.

- There is no clear differentiation in MSRP between CAFV-eligible vehicles and those that are either not eligible or have unknown eligibility. This suggests that base price does not necessarily correlate with a vehicle's eligibility for Clean Alternative Fuel Vehicle incentives.

Analyze the Relationship Between CAFV Eligibility and Electric Range
"""

# Group by CAFV Eligibility and calculate the mean Electric Range
range_summary_by_cafv = df.groupby('Clean Alternative Fuel Vehicle (CAFV) Eligibility')['Electric Range'].describe()

# Display the summary statistics
print(range_summary_by_cafv)

# Box plot of Electric Range by CAFV Eligibility
plt.figure(figsize=(10, 6))
sns.boxplot(x='Clean Alternative Fuel Vehicle (CAFV) Eligibility', y='Electric Range', data=df, palette='Set2')
plt.title('Electric Range by CAFV Eligibility')
plt.xlabel('CAFV Eligibility')
plt.ylabel('Electric Range (miles)')
plt.show()

"""**Findings**

- Vehicles that are eligible for Clean Alternative Fuel Vehicle incentives have the highest median and overall electric range. The median electric range for these vehicles is around 150 miles, with the interquartile range extending from about 100 to over 200 miles. Some vehicles in this category even exceed 300 miles.

- Vehicles that are not eligible due to low battery range have a very limited electric range, with a median of around 20 miles and a narrow range between 0 to 50 miles. This category is clearly distinct from the CAFV eligible vehicles in terms of electric range.

- Vehicles with unknown eligibility due to unresearched battery range generally have very low electric ranges, similar to those not eligible. This could indicate that these vehicles are either older models or have incomplete data regarding their electric capabilities.
"""

# Scatter plot of Base MSRP vs. Electric Range, colored by CAFV Eligibility
plt.figure(figsize=(12, 8))
sns.scatterplot(x='Electric Range', y='Base MSRP', hue='Clean Alternative Fuel Vehicle (CAFV) Eligibility', data=df, palette='Set1', alpha=0.7)
plt.title('Base MSRP vs. Electric Range by CAFV Eligibility')
plt.xlabel('Electric Range (miles)')
plt.ylabel('Base MSRP ($)')
plt.legend(title='CAFV Eligibility')
plt.show()

"""**Findings**

- Vehicles that are eligible for CAFV incentives (represented in red) tend to have higher base MSRPs, especially as the electric range increases. For ranges around 200 miles and above, the base MSRP is concentrated between $40,000 and $50,000.

- Vehicles that are not eligible due to low battery range (represented in blue) generally have lower electric ranges (below 100 miles). These vehicles also show a high base MSRP, suggesting that high cost does not necessarily correlate with high electric range for non-eligible vehicles.

- Vehicles with unknown eligibility due to unresearched battery range (represented in green) typically have very low electric ranges and base MSRPs close to zero, indicating that these may be older models or data with incomplete entries.

- There is a distinct clustering of vehicles with low electric ranges (under 50 miles) and low base MSRPs. This cluster includes a mix of both eligible and non-eligible vehicles, showing that lower-end vehicles with shorter ranges are common in the market.

# **Insights and Recommendations**

1. Distribution of BEVs vs. PHEVs
Insight:
- Battery Electric Vehicles (BEVs) dominate the market with over 150,000 vehicles registered, compared to around 50,000 Plug-in Hybrid Electric Vehicles (PHEVs).

Recommendation:
- Focusing on expanding charging infrastructure specifically for BEVs, as they represent the majority of the market. However, maintain some support for PHEVs, especially in areas with lower charging availability.


2. BEVs vs. PHEVs Distribution by County
Insight:
- King County has the highest number of BEVs with over 90,000 vehicles, and a significant but smaller number of PHEVs, around 25,000 vehicles. Other counties such as Snohomish and Pierce also show moderate adoption, but with much lower numbers (around 10,000 BEVs each).

Recommendation:
- Continuing investment in King County’s EV infrastructure to support its large EV population. Consider targeted campaigns in Snohomish and Pierce counties to boost adoption further, leveraging their already significant EV populations.


3. Top 10 Most Popular EV Makes
Insight:
- Tesla is by far the most popular make, with over 90,000 vehicles, followed by Chevrolet and Nissan with approximately 20,000 and 15,000 vehicles, respectively.

Recommendation:
- Manufacturers like Tesla should be key partners in any EV infrastructure development or promotional campaigns. Also, consider support for other popular brands like Chevrolet and Nissan to diversify the market.


4. Top 10 Most Popular EV Models
Insight:
- The Tesla Model Y is the most popular model with over 40,000 vehicles, followed by the Tesla Model 3 with around 30,000 vehicles. The Nissan Leaf comes in third with about 15,000 vehicles.

Recommendation:
- Highlighting the popularity of these top models in marketing efforts to potential new EV adopters. Provide incentives for these models, which have already shown high consumer acceptance.


5. Distribution of Electric Range
Insight:
- The majority of vehicles have an electric range of under 50 miles, but there is a significant number of vehicles with ranges of 200-300 miles, indicating a mix of short-range and long-range EVs in the market.

Recommendation:
- Focusing on promoting and supporting vehicles with longer ranges (200-300 miles) as they align better with consumer expectations and reduce range anxiety. This can be done through incentives or public awareness campaigns.


6. Most Popular Car Maker by County
Insight:
- Tesla is the dominant car maker across most counties, with a significant presence in King County (over 30,000 vehicles), Snohomish County (around 10,000 vehicles), and Pierce County (around 8,000 vehicles).

Recommendation:
- Giving Tesla's dominance, ensure Tesla-specific charging infrastructure is robust and accessible. Collaborate with Tesla for future infrastructure projects and consumer incentives in these key counties.


7. Most Popular Car Maker by City
Insight:
- Tesla also leads in most cities, with Seattle showing the highest number of Tesla vehicles (over 10,000 vehicles), followed by cities like Bellevue and Redmond with lower but significant numbers.

Recommendation:
- Targeting Seattle, Bellevue, and Redmond for further infrastructure investments and promotional activities, especially in collaboration with Tesla, to maintain and grow EV adoption rates.


8. Growth of Top Makes and Models by Year
Insight:
- The Tesla Model 3 and Model Y have seen sharp increases in adoption, especially around 2020-2021. Other models like the Nissan Leaf and Chevrolet Bolt EV have seen steady but slower growth.

Recommendation:
- Focusing on understanding the factors behind Tesla’s growth surge and apply similar strategies to other models. Continue to support the growth of other models to avoid market over-concentration on a single brand.


9. Average Base MSRP by Car Maker
Insight:
- The Wheego Electric Cars brand has the highest average base MSRP at $32,995. However, many brands, including Tesla, show $0 MSRP, possibly indicating incomplete data.

Recommendation:
- Investigating the data completeness for MSRPs and update the database if needed. Accurate pricing information is crucial for developing targeted incentives and understanding consumer preferences.


10. Distribution of Base MSRP by County
Insight:
- Base MSRP distribution varies widely across counties, with King County and Los Angeles County showing the widest range of MSRPs.

Recommendation:
- Tailored incentives and marketing strategies to fit the economic profiles of different counties, recognizing that some areas have a higher concentration of high-MSRP vehicles.


11. Base MSRP by EV Type (BEV vs. PHEV)
Insight:
- BEVs tend to have a slightly higher base MSRP compared to PHEVs. Some outliers reach over $50,000, indicating premium EVs in the market.

Recommendation:
- Focusing on promoting high-end BEVs in more affluent markets while ensuring that affordable PHEVs are available in regions with lower average incomes.


12. Distribution of Electric Range by Make
Insight:
- Tesla vehicles dominate the longer-range category, particularly in the 200-300 mile range, while other brands like Nissan and Chevrolet show significant numbers in the 100-200 mile range.

Recommendation:
- Promoting longer-range Tesla models in areas where infrastructure is robust, and encourage adoption of mid-range vehicles from other brands in developing EV markets.


13. CAFV Eligibility vs. Non-Eligibility by County
Insight:
- King County has the highest number of CAFV-eligible vehicles (over 40,000), while other counties like Snohomish and Pierce also show significant numbers but with a larger portion of non-eligible vehicles.

Recommendation:
- Increasing efforts to make more vehicles CAFV-eligible in counties with lower eligibility rates. This could involve lobbying for policy changes or improving infrastructure to support a broader range of EVs.


14. CAFV Eligibility vs. Non-Eligibility by City
Insight:
- Seattle has the highest number of CAFV-eligible vehicles (around 10,000), but many vehicles still fall into the non-eligible category due to low battery range or unresearched eligibility.

Recommendation:
- Working with local governments in cities like Seattle to improve CAFV eligibility, either by promoting vehicles with higher ranges or ensuring that eligibility research is up to date.


15. Base MSRP by CAFV Eligibility
Insight:
- CAFV-eligible vehicles generally have a higher MSRP, often exceeding $40,000, indicating that these vehicles are positioned as premium options within the market.

Recommendation:
- To make EVs more accessible, consider introducing incentives aimed at reducing the cost barrier for CAFV-eligible vehicles, particularly in less affluent regions.


16. Electric Range by CAFV Eligibility
Insight:
- CAFV-eligible vehicles tend to have a higher electric range, with a median around 150 miles and extending up to 300 miles.

Recommendation:
- Continuing promoting vehicles that meet CAFV eligibility criteria and offer substantial electric range, as they align with consumer expectations and policy goals for reducing emissions.


17. Base MSRP vs. Electric Range by CAFV Eligibility
Insight:
- There is a clear relationship between higher electric range and higher MSRP among CAFV-eligible vehicles. Vehicles with ranges over 200 miles tend to cost $40,000 or more.

Recommendation:
- Leveraging this correlation by providing targeted incentives for high-range, high-cost vehicles in regions where infrastructure can support them, ensuring that these vehicles remain attractive to consumers despite their higher price points.
"""